### ISSUE TITLE
WebSocket stops updating?

### ISSUE THREAD

**Issue by mkmer** [tomwpublic/hubitat_aladdinConnect#13]
I'm not sure how else to get a hold of you - I've mostly copied your work and mashed it with shoejosh's into a new AIOAladdinConnect api for HomeAssistant.  

The problem I've noticed is around 2AM EST every day, the socket receives a "standard" closed message, no errors, but then never sends another state change message afterwards.  Whenever a poll occurs of battery or RSSI, I now have to compare and restart the websocket if it's not a match, but still miss open/close sequences when they are between polls. 

Are you guys seeing similar issues with this API after 24 hours?

**Comment by tomwpublic** [comment]
The server closing a socket is a normal occurance. It may be closing it, for example, to regularly ensure that when you reconnect you are still authorized.

You need to add some logic to reconnect (and re-auth first, if necessary) in response to the socket closing.

**Comment by mkmer** [comment]
Yes, I understand that, but the socket is not being closed, it's still open
but no new events are sent via the socket.  If it had closed, the task
reconnects.
The reauth is occurring roughly 24 hours +/-.  After a reauth my API closes
the socket, gets a new key, and reconnects everything (and starts working
again).  Additionally, my version verifies the door state on a polled
update, if they don't match, it reconnects the web socket with the existing
key.  Unfortunately, the polled update is every 5 minutes, so it doesn't
always catch a mismatch (say you open/close the door in under 5 minutes).

I've also noticed 2 or 3 event messages coming through the socket (all with
the same "state" when the door changes state).  Wonder if they are
expecting some sort of application level ack.

That said, you are not seeing issues with the websocket not keeping you up
to date?  I suppose if your key is expiring between 12AM and 6AM, you may
never notice?!?

Thanks!

**Comment by tomwpublic** [comment]
Ah, I understand better now.

I use the expires_in field from the token response to schedule the re-auth. And I schedule it early with a lot of margin, because it isn't a lot of overhead if you do it more often than required.

Maybe that is either avoiding and/or masking the behavior you're seeing.

Regardless, with that scheme, I haven't heard any users experiencing missed events.

If that doesn't help, please join us in this thread and we can ask whether any of my users are seeing similar issues. 
https://community.hubitat.com/t/is-it-possible-to-use-rm4-to-control-report-on-my-genie-aladdin-garage-based-on-postman-success/45619/6
